services:
  mongodb:
    image: mongo:8
    container_name: chatbot-service
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chatbot-rabbitmq
    ports:
      - "5672:5672"   # conexión de la app
      - "15672:15672" # panel de administración web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data: